void gnutls_certificate_client_set_retrieve_function(gnutls_certificate_credentials_t cred, gnutls_certificate_client_retrieve_function *func) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_certificate_server_set_retrieve_function(gnutls_certificate_credentials_t cred, gnutls_certificate_server_retrieve_function *func) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_sign_callback_set(gnutls_session_t session, gnutls_sign_func sign_func, void *userdata) _GNUTLS_GCC_ATTR_DEPRECATED;
gnutls_sign_func gnutls_sign_callback_get(gnutls_session_t session, void **userdata) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_ext_register(int type, const char *name, gnutls_ext_parse_type_t parse_type, gnutls_ext_recv_func recv_func, gnutls_ext_send_func send_func) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_session_set_finished_function(gnutls_session_t session, gnutls_finished_callback_func func) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_psk_netconf_derive_key(const char *password, const char *psk_identity, const char *psk_identity_hint, gnutls_datum_t *output_key) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_privkey_sign_hash(gnutls_x509_privkey_t key, const gnutls_datum_t *hash, gnutls_datum_t *signature) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_openpgp_privkey_sign_hash(gnutls_openpgp_privkey_t key, const gnutls_datum_t *hash, gnutls_datum_t *signature) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_privkey_verify_data(gnutls_x509_privkey_t key, unsigned int flags, const gnutls_datum_t *data, const gnutls_datum_t *signature) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_privkey_sign_data(gnutls_x509_privkey_t key, gnutls_digest_algorithm_t digest, unsigned int flags, const gnutls_datum_t *data, void *signature, size_t *signature_size) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crt_verify_data(gnutls_x509_crt_t crt, unsigned int flags, const gnutls_datum_t *data, const gnutls_datum_t *signature) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crt_verify_hash(gnutls_x509_crt_t crt, unsigned int flags, const gnutls_datum_t *hash, const gnutls_datum_t *signature) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crt_get_verify_algorithm(gnutls_x509_crt_t crt, const gnutls_datum_t *signature, gnutls_digest_algorithm_t *hash) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crt_get_preferred_hash_algorithm(gnutls_x509_crt_t crt, gnutls_digest_algorithm_t *hash, unsigned int *mand) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crq_sign2(gnutls_x509_crq_t crq, gnutls_x509_privkey_t key, gnutls_digest_algorithm_t dig, unsigned int flags) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crq_sign(gnutls_x509_crq_t crq, gnutls_x509_privkey_t key) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crl_sign(gnutls_x509_crl_t crl, gnutls_x509_crt_t issuer, gnutls_x509_privkey_t issuer_key) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_x509_crl_sign2(gnutls_x509_crl_t crl, gnutls_x509_crt_t issuer, gnutls_x509_privkey_t issuer_key, gnutls_digest_algorithm_t dig, unsigned int flags) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_certificate_get_x509_cas(gnutls_certificate_credentials_t sc, gnutls_x509_crt_t **x509_ca_list, unsigned int *ncas) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_certificate_get_x509_crls(gnutls_certificate_credentials_t sc, gnutls_x509_crl_t **x509_crl_list, unsigned int *ncrls) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_certificate_get_openpgp_keyring(gnutls_certificate_credentials_t sc, gnutls_openpgp_keyring_t *keyring) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_certificate_verify_peers(gnutls_session_t session) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_cipher_set_priority(gnutls_session_t session, const int *list) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_mac_set_priority(gnutls_session_t session, const int *list) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_compression_set_priority(gnutls_session_t session, const int *list) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_kx_set_priority(gnutls_session_t session, const int *list) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_protocol_set_priority(gnutls_session_t session, const int *list) _GNUTLS_GCC_ATTR_DEPRECATED;
int gnutls_certificate_type_set_priority(gnutls_session_t session, const int *list) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_transport_set_lowat(gnutls_session_t session, int num) _GNUTLS_GCC_ATTR_DEPRECATED;
void gnutls_transport_set_global_errno(int err) _GNUTLS_GCC_ATTR_DEPRECATED;
