int gnutls_cipher_init(gnutls_cipher_hd_t *handle, gnutls_cipher_algorithm_t cipher, const gnutls_datum_t *key, const gnutls_datum_t *iv);
int gnutls_cipher_encrypt(const gnutls_cipher_hd_t handle, void *text, size_t textlen);
int gnutls_cipher_decrypt(const gnutls_cipher_hd_t handle, void *ciphertext, size_t ciphertextlen);
int gnutls_cipher_decrypt2(gnutls_cipher_hd_t handle, const void *ciphertext, size_t ciphertextlen, void *text, size_t textlen);
int gnutls_cipher_encrypt2(gnutls_cipher_hd_t handle, void *text, size_t textlen, void *ciphertext, size_t ciphertextlen);
void gnutls_cipher_deinit(gnutls_cipher_hd_t handle);
int gnutls_cipher_get_block_size(gnutls_cipher_algorithm_t algorithm);
int gnutls_hmac_init(gnutls_hmac_hd_t *dig, gnutls_digest_algorithm_t algorithm, const void *key, size_t keylen);
int gnutls_hmac(gnutls_hmac_hd_t handle, const void *text, size_t textlen);
void gnutls_hmac_output(gnutls_hmac_hd_t handle, void *digest);
void gnutls_hmac_deinit(gnutls_hmac_hd_t handle, void *digest);
int gnutls_hmac_get_len(gnutls_mac_algorithm_t algorithm);
int gnutls_hmac_fast(gnutls_mac_algorithm_t algorithm, const void *key, size_t keylen, const void *text, size_t textlen, void *digest);
int gnutls_hash_init(gnutls_hash_hd_t *dig, gnutls_digest_algorithm_t algorithm);
int gnutls_hash(gnutls_hash_hd_t handle, const void *text, size_t textlen);
void gnutls_hash_output(gnutls_hash_hd_t handle, void *digest);
void gnutls_hash_deinit(gnutls_hash_hd_t handle, void *digest);
int gnutls_hash_get_len(gnutls_digest_algorithm_t algorithm);
int gnutls_hash_fast(gnutls_digest_algorithm_t algorithm, const void *text, size_t textlen, void *digest);
int gnutls_rnd(gnutls_rnd_level_t level, void *data, size_t len);
void gnutls_pk_params_release(gnutls_pk_params_st *p);
void gnutls_pk_params_init(gnutls_pk_params_st *p);
int gnutls_crypto_single_cipher_register2(gnutls_cipher_algorithm_t algorithm, int priority, int version, const gnutls_crypto_single_cipher_st *s);
int gnutls_crypto_single_mac_register2(gnutls_mac_algorithm_t algorithm, int priority, int version, const gnutls_crypto_single_mac_st *s);
int gnutls_crypto_single_digest_register2(gnutls_digest_algorithm_t algorithm, int priority, int version, const gnutls_crypto_single_digest_st *s);
int gnutls_crypto_cipher_register2(int priority, int version, const gnutls_crypto_cipher_st *s);
int gnutls_crypto_mac_register2(int priority, int version, const gnutls_crypto_mac_st *s);
int gnutls_crypto_digest_register2(int priority, int version, const gnutls_crypto_digest_st *s);
int gnutls_crypto_rnd_register2(int priority, int version, const gnutls_crypto_rnd_st *s);
int gnutls_crypto_pk_register2(int priority, int version, const gnutls_crypto_pk_st *s);
int gnutls_crypto_bigint_register2(int priority, int version, const gnutls_crypto_bigint_st *s);
