int gnutls_pkcs11_init(unsigned int flags, const char *configfile);
void gnutls_pkcs11_deinit(void);
void gnutls_pkcs11_set_token_function(gnutls_pkcs11_token_callback_t fn, void *userdata);
void gnutls_pkcs11_set_pin_function(gnutls_pkcs11_pin_callback_t fn, void *userdata);
int gnutls_pkcs11_add_provider(const char *name, const char *params);
int gnutls_pkcs11_obj_init(gnutls_pkcs11_obj_t *obj);
int gnutls_pkcs11_obj_import_url(gnutls_pkcs11_obj_t, const char *url, unsigned int flags);
int gnutls_pkcs11_obj_export_url(gnutls_pkcs11_obj_t obj, gnutls_pkcs11_url_type_t detailed, char **url);
void gnutls_pkcs11_obj_deinit(gnutls_pkcs11_obj_t obj);
int gnutls_pkcs11_obj_export(gnutls_pkcs11_obj_t obj, void *output_data, size_t *output_data_size);
int gnutls_pkcs11_copy_x509_crt(const char *token_url, gnutls_x509_crt_t crt, const char *label, unsigned int flags);
int gnutls_pkcs11_copy_x509_privkey(const char *token_url, gnutls_x509_privkey_t key, const char *label, unsigned int key_usage , unsigned int flags);
int gnutls_pkcs11_delete_url(const char *object_url, unsigned int flags);
int gnutls_pkcs11_copy_secret_key(const char *token_url, gnutls_datum_t *key, const char *label, unsigned int key_usage , unsigned int flags);
int gnutls_pkcs11_obj_get_info(gnutls_pkcs11_obj_t crt, gnutls_pkcs11_obj_info_t itype, void *output, size_t *output_size);
int gnutls_pkcs11_token_init(const char *token_url, const char *so_pin, const char *label);
int gnutls_pkcs11_token_get_mechanism(const char *url, int idx, unsigned long *mechanism);
int gnutls_pkcs11_token_set_pin(const char *token_url, const char *oldpin, const char *newpin, unsigned int flags);
int gnutls_pkcs11_token_get_url(unsigned int seq, gnutls_pkcs11_url_type_t detailed, char **url);
int gnutls_pkcs11_token_get_info(const char *url, gnutls_pkcs11_token_info_t ttype, void *output, size_t *output_size);
int gnutls_pkcs11_token_get_flags(const char *url, unsigned int *flags);
int gnutls_pkcs11_obj_list_import_url(gnutls_pkcs11_obj_t *p_list, unsigned int *const n_list, const char *url, gnutls_pkcs11_obj_attr_t attrs, unsigned int flags);
int gnutls_x509_crt_import_pkcs11(gnutls_x509_crt_t crt, gnutls_pkcs11_obj_t pkcs11_crt);
int gnutls_x509_crt_import_pkcs11_url(gnutls_x509_crt_t crt, const char *url, unsigned int flags);
gnutls_pkcs11_obj_type_t gnutls_pkcs11_obj_get_type(gnutls_pkcs11_obj_t certificate);
int gnutls_x509_crt_list_import_pkcs11(gnutls_x509_crt_t *certs, unsigned int cert_max, gnutls_pkcs11_obj_t *const objs, unsigned int flags);
int gnutls_pkcs11_privkey_init(gnutls_pkcs11_privkey_t *key);
void gnutls_pkcs11_privkey_deinit(gnutls_pkcs11_privkey_t key);
int gnutls_pkcs11_privkey_get_pk_algorithm(gnutls_pkcs11_privkey_t key, unsigned int *bits);
int gnutls_pkcs11_privkey_get_info(gnutls_pkcs11_privkey_t pkey, gnutls_pkcs11_obj_info_t itype, void *output, size_t *output_size);
int gnutls_pkcs11_privkey_import_url(gnutls_pkcs11_privkey_t pkey, const char *url, unsigned int flags);
int gnutls_pkcs11_privkey_export_url(gnutls_pkcs11_privkey_t key, gnutls_pkcs11_url_type_t detailed, char **url);
