#!/usr/bin/perl -w
#-
# brian m. carlson <sandals@crustytoothpaste.ath.cx> wrote this source code.
# This source code is in the public domain; you may do whatever you please with
# it.  However, a credit in the documentation, although not required, would be
# appreciated.

sub generate_data {
	my ($line) = @_;

	return (undef, undef)
		unless $line =~ m/^([A-Za-z0-9-()]+)\s*:.*\((\d+\.\d+)\s+MiB\/s\).*$/;
	return ($1, $2 + 0.0);
}

if (scalar @ARGV < 2) {
	print STDERR <<EOM;
usage: compare-speed old new [factor]

old and new are the output of 'make speed'
factor (default 1.0) is an adjustment to new's speed
\tthat is, old and (new/factor) are the values computed
EOM
	exit 2;
}

$factor = 1.0;
open(OLD, "<$ARGV[0]") or die "cannot open file: $!";
@oldbuf = <OLD>;
close(OLD);
open(NEW, "<$ARGV[1]") or die "cannot open file: $!";
@newbuf = <NEW>;
$factor = $ARGV[2] + 0.0 if (scalar @ARGV >= 3);
close(NEW);

@items = ();
%algos = ();

for my $line (@oldbuf) {
	my ($tag, $speed) = generate_data($line);
	next unless defined $tag;
	push @items, $tag;
	unless (exists $algos{$tag}) {
		$algos{$tag} = [];
	}
	push @{$algos{$tag}}, $speed;
}

%counts = map { ($_, 0) } @items;
for my $line (@newbuf) {
	my ($tag, $new) = generate_data($line);
	next unless defined $tag;

	my $cnt = $counts{$tag}++;
	my $old = $algos{$tag}[$cnt];

	next unless $old;

	$new /= $factor;
	$v = (($new - $old) / $old) * 100.0;
	printf "%-16s: change is %7.3f%%\n", $tag, $v;
}
